name: 'Ru NPM tests'
description: 'Workflow to execute npm test command with MongoDB container running in the background'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'
        cache: 'npm'
    - uses: actions/cache@v2
      id: cache-node-modules
      with:
        path: 'node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('package.json') }}

    # Configure credentials
    - name: Create NPMRC
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      env:
        NPMRC: ${{ secrets.NPMRC }}
      run: echo "$NPMRC" > .npmrc
    - name: Install SSH Key
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.GH_SSH_PRIVATE_KEY }} 
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
    - name: NPM Install
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      run: npm install
    - name: Print debug logs
      if: ${{ failure() }}
      run: cat ~/.npm/_logs/*

    # Git push package-lock.json if someone forgot to push it
    - name: Git user identification
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      run: git config user.email "ghactions@debitoor.com" && git config user.name "GH Actions"
    - name: Checkout package.json
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      run: git checkout package.json
    - name: Git push
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      run: var=$(git status | grep package-lock.json | wc -l) && [ ! -z $var ] && git add package-lock.json && git commit -m "update pkg lock" && git push origin $GITHUB_REF_NAME || git status

    # Run test  
    - name: Test
      run: npm test

   # Collect results
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
        files: '**/mocha/*.xml'
