name: 'Deploy to Heroku'
description: 'Workflow to trigger build in Heroku'

inputs:
  heroku-app-name:
    description: 'Heroku app name'
    required: true
  heroku-api-key:
    description: 'Heroku API key'
    required: true
  heroku-email:
    description: 'Email'
    required: false
    default: bob@debitoor.com

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{ inputs.heroku-api-key}}
        heroku_app_name: ${{ inputs.heroku-app-name }}
        heroku_email: ${{ inputs.heroku-email }}
        justlogin: true
        
    - name: Add Heroku Git remote
      run: heroku git:remote -r heroku -a ${{ inputs.heroku-app-name }}
      shell: bash

    - name: Report branch to be pushed
      run: echo "Pushing from $GITHUB_HEAD_REF"
      shell: bash

    # Push to Heroku git, git always write to stderr so redirect it to stdout and then to file and run in background
    - name: Push to Heroku Git
      run: git push -f heroku $GITHUB_REF_NAME:master > temp 2>&1 &
      shell: bash

    # Wait for Heroku response that build process has been started (exit grep after first match)
    - name: Wait for deployment to start
      run: |
        tail -f -n 1000 temp &
        grep -m 1 -E -i "(building)|(Everything up-to-date)|(failed to push)" <(tail -f -n 1000 temp) 
      shell: bash
