name: Tag release

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:
    inputs:
      tag-name:
        description: 'Tag name'     
        required: true
        default: 'test'
        
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0 # fetch all history to get the latest tag

      - name: Configure Git
        run: |
          git config --global user.email "ops@debitoor.com"
          git config --global user.name "Debitoor OPS"
      
      - name: Find latest tag
        if: inputs.tag-name == null
        id: find_tag
        run: echo ::set-output name=tag::$(git describe --tags --abbrev=0)

      - name: Bump tag
        if: inputs.tag-name == null
        id: bump_tag
        # example of below commands result: v2.1 -> (cut) -> 2.1 -> (awk) -> 2 2 -> (sed) -> 2.2
        run: echo ::set-output name=tag::v$(echo ${{ steps.find_tag.outputs.tag }} | cut -d'v' -f2 | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')

      - name: Tag source
        env:
          TAG_NAME: ${{ inputs.tag-name || steps.bump_tag.outputs.tag }}
        run: git tag -am v"${TAG_NAME}" v"${TAG_NAME}"

      - name: Push tag
        run: git push --tags
